first try
MistakeLive/Server pull request #2
Opened 2018-08-30 11:06 UTC by MistakeLive

2018-09-02 21:05 UTC, MistakeLive commented
TODO:
-пропарсить мета данные для duratation
-сделать возможность добавление треков
-фикс бага с перемоткой

2018-09-03 18:56 UTC, vgvoleg requested changes

2018-09-03 18:56 UTC, vgvoleg commented on src/main/java/serv/controllers/SongBaseController.java
> +    public Vector<String> list() {
Замени, пожалуйста, Vector на List с любой имплементацией. Вектор помечен как deprecated, его использовать не стоит, ибо он старше нас с тобой

2018-09-03 18:56 UTC, vgvoleg commented on src/main/java/serv/controllers/SongBaseController.java
> +    public Vector<String> list() {
Ну и везде, где его используешь

2018-09-03 18:56 UTC, vgvoleg commented on src/main/java/serv/controllers/SongBaseController.java
> +        return songRepo.findBysongName(name).get(0).getSongFile();
get(0) говорит о том, что ты что-то делаешь не так)
песен может и не быть, тогда программа упадет
а если тебе нужна первая попавшаяся, то лучше получение списка и отдельной песни разбить на 2 отдельных метода

2018-09-03 18:56 UTC, vgvoleg commented on src/main/java/serv/controllers/SongBaseController.java
> +    public Vector list1() {
давай более осмысленный метод функциям
если упадет ошибка, то в стектрейсе ты будешь видеть вызовы функций list(), list1(), переменные v, v1 ну ты понял мою мысль

2018-09-03 18:56 UTC, vgvoleg commented on src/main/java/serv/controllers/SongBaseController.java
> +        for (int i = 0; i < list.size(); i++) {
для циклов, где работать с индексом тебе не нужно, лучше использовать for .. in

2018-09-03 18:56 UTC, vgvoleg commented on src/main/java/serv/controllers/SongBaseController.java
> +        return v;
мне кажется, можно просто иметь один метод, который отправляет метаинформацию о песне, и на клиенте доставать лишь нужное, нежели писать новый метод на каждый кейс с клиента

2018-09-03 18:56 UTC, vgvoleg commented on src/main/resources/static/index.html
> +<!doctype html>
дружище абажжди, я все еще в репозитории Server, почему тут верстка и другая фронтенд часть?)

2018-09-05 18:49 UTC, vgvoleg requested changes

2018-09-05 18:49 UTC, vgvoleg commented on src/main/java/serv/controllers/SongBaseController.java
> +        List songList = new ArrayList();
List < ?? >

2018-09-05 18:49 UTC, vgvoleg commented on src/main/java/serv/controllers/SongBaseController.java
> +    public List<String> returningSongsList() {
getSongsList

2018-09-05 18:49 UTC, vgvoleg commented on src/main/java/serv/controllers/SongBaseController.java
> +    public List<String> returningSongsList() {
getSongsNameList

2018-09-05 18:49 UTC, vgvoleg commented on src/main/java/serv/controllers/SongBaseController.java
> +            if (!attachFileObj.getOriginalFilename().equals("")) {
String.equals(s1, s2)

2018-09-05 18:49 UTC, vgvoleg commented on src/main/java/serv/controllers/SongBaseController.java
> +    public void addSongtoBase(@RequestParam("file") MultipartFile attachFileObj) throws Exception{
запись файла и запись названия и исполнителя отдельными полями в методе post

2018-09-05 18:49 UTC, vgvoleg commented on src/main/java/serv/controllers/SongBaseController.java
> +    public List returningSongsAndDurationList() {
Song как json (вместо файла песни id - ссылка на другую таблицу)

2018-09-05 18:49 UTC, vgvoleg commented on src/main/java/serv/entity/Song.java
>      private byte[] songFile;
songFile => songFileId

2018-09-10 19:49 UTC, vgvoleg requested changes

2018-09-10 19:49 UTC, vgvoleg commented on src/main/java/serv/controllers/SongBaseController.java
> +    public List getSongsInfo() {
опять джнерики убрал

2018-09-10 19:52 UTC, MistakeLive commented on src/main/java/serv/controllers/SongBaseController.java
> +        List songList = new ArrayList();
done

2018-09-10 19:53 UTC, MistakeLive commented on src/main/java/serv/controllers/SongBaseController.java
> +    public List<String> returningSongsList() {
done

2018-09-10 19:53 UTC, MistakeLive commented on src/main/java/serv/controllers/SongBaseController.java
> +            if (!attachFileObj.getOriginalFilename().equals("")) {
not done, one moment

2018-09-10 19:53 UTC, MistakeLive commented on src/main/java/serv/controllers/SongBaseController.java
> +    public void addSongtoBase(@RequestParam("file") MultipartFile attachFileObj) throws Exception{
done

2018-09-10 19:53 UTC, MistakeLive commented on src/main/java/serv/controllers/SongBaseController.java
> +    public List returningSongsAndDurationList() {
done

2018-09-10 19:53 UTC, MistakeLive commented on src/main/java/serv/entity/Song.java
>      private byte[] songFile;
done

2018-09-10 19:54 UTC, MistakeLive commented on src/main/java/serv/controllers/SongBaseController.java
> +    public List getSongsInfo() {
что то там падало, надо глянуть и верну
забыл уже

2018-10-02 20:17 UTC, vgvoleg approved these changes

2018-10-02 20:17 UTC, merged